import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Toaster } from 'react-hot-toast';
import SessionContext from '@/Context/session-context';
import '@/app/globals.css';
import { ThemeProvider } from '@/Provider/ThemeProvider';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-primary text-primary-foreground`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem>
          <SessionContext>
            {children}
            <Toaster />
          </SessionContext>
        </ThemeProvider>
      </body>
    </html>
  )
}
